{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $content=$content|explode( "\n" )}
<pre{section show=ne($classification|trim,'')} class="{$classification|wash}"{/section}>{foreach $content as $line}<span class="line">{$line|wash(xhtml)}{"\n"}</span>{/foreach}<span class="line">{"\n"}</span></pre>
